//
//  WorkflowDirectory.swift
//  workflow-manager
//
//  `.taskboard/` inside a linked repository: the shared surface between this app
//  and a Claude Code session running in that repo.
//
//  The name is deliberately *not* `.workflow` — that collides with how everyone
//  reads "workflow" (GitHub Actions, CI). `.taskboard` says what the directory
//  is: the board's task mirror and the contract that goes with it. It is the one
//  place the on-disk name is defined; the contract text below derives from it.
//
//  It lives in the repo because a session started there has to find it by
//  convention — `claude remote-control` takes no prompt, so there is no way to
//  hand it a path. It is ignored by git because GitHub issues are the team's
//  layer and this is local AI-work state; committing it would also mean merge
//  conflicts on a file two programs rewrite.
//

import Foundation

nonisolated enum WorkflowDirectory {
    static let name = ".taskboard"

    /// Repository-relative paths, so every mention in the UI and the agent
    /// contract stays in step with `name` instead of hardcoding it.
    static var tasksPath: String { "\(name)/tasks.json" }
    static var readmePath: String { "\(name)/README.md" }
    static var examplePath: String { "\(name)/example.json" }

    static func url(in repository: URL) -> URL {
        repository.appending(path: name, directoryHint: .isDirectory)
    }

    static func tasksURL(in repository: URL) -> URL {
        url(in: repository).appending(path: "tasks.json")
    }

    static func sessionLogURL(in repository: URL) -> URL {
        url(in: repository).appending(path: "session.log")
    }

    static func sessionInfoURL(in repository: URL) -> URL {
        url(in: repository).appending(path: "session.json")
    }

    static func readmeURL(in repository: URL) -> URL {
        url(in: repository).appending(path: "README.md")
    }

    static func exampleURL(in repository: URL) -> URL {
        url(in: repository).appending(path: "example.json")
    }

    /// Creates the directory and its self-ignoring `.gitignore`.
    ///
    /// The `.gitignore` holds a single `*`, which ignores the directory's whole
    /// contents *including itself*. That keeps the repository's own committed
    /// `.gitignore` untouched — an app must not silently edit a file the user
    /// has checked in.
    static func ensure(in repository: URL) throws {
        let directory = url(in: repository)
        try FileManager.default.createDirectory(
            at: directory,
            withIntermediateDirectories: true
        )

        let gitignore = directory.appending(path: ".gitignore")
        guard !FileManager.default.fileExists(atPath: gitignore.path(percentEncoded: false)) else {
            return
        }
        try Data("*\n".utf8).write(to: gitignore, options: .atomic)
    }

    // MARK: - The agent contract
    //
    // `claude remote-control` accepts no prompt, so everything the agent needs
    // to know has to be readable from the repository. Both documents below are
    // shown to the user in full and written only on confirmation.

    // These two are identifiers, not prose: they are already sitting in other
    // people's `CLAUDE.md` files, and `applyingMemorySnippet(to:)` finds the
    // previous block by matching them. Renaming them to match the product's
    // "Claude WM" name would make every existing block invisible and get a
    // second one appended below it.
    static let claudeMemoryBeginMarker = "<!-- workflow-manager:begin -->"
    static let claudeMemoryEndMarker = "<!-- workflow-manager:end -->"

    /// The contract itself, written to `\(name)/README.md`.
    ///
    /// The rules are stated as things that go wrong, not as a schema, because
    /// every one of them below has actually happened: the decoder is deliberately
    /// tolerant — an unknown status becomes `todo`, a missing timestamp becomes
    /// now — so a wrong file is *accepted* and quietly means something else. The
    /// worked example is generated by the real encoder for the same reason: prose
    /// about a shape gets reinterpreted, a file does not.
    static func readme(projectName: String, repositorySlug: String?) -> String {
        """
        # Workflow tasks

        `tasks.json` in this directory mirrors the **\(projectName)** board in
        Claude WM\(repositorySlug.map { " for `\($0)`" } ?? ""). The app watches this file; edits
        you make here show up on the board within a second.

        `example.json` beside it is a complete, valid file — the same bytes the
        app itself writes. **Read it before your first edit.** It is an example,
        not input: nothing reads it, and editing it does nothing.

        ## Read this first: five ways to break it silently

        Nothing here throws. A malformed file is *accepted* and means something
        you did not intend, so these are the rules that matter:

        1. **Never invent or change an `id`.** It is the board card's identity.
           A row you edited under a new id becomes a **second card**, and the
           original stays where it was. Copy ids through verbatim, including
           their letter case.
        2. **Never drop a key you don't understand** — `tombstones` above all.
           It is how the app remembers cards the user deleted; write the file
           without it and a deleted card can come back.
        3. **Statuses are spelled exactly `todo`, `in_progress`, `review`,
           `done`.** `in-progress`, `inProgress`, `blocked` and `Done` are not
           rejected — they are silently read as `todo`, which moves the card
           backwards.
        4. **Timestamps are ISO-8601 with a `Z` and no fractional seconds** —
           `2026-01-05T10:30:00Z`. `…T10:30:00.123Z` fails to parse and the
           field falls back to the current time.
        5. **Never create `tasks.json` yourself.** The app writes it the moment
           sync is switched on, seeded with the board's real cards and their
           real ids. A file you write first is not ignored — every row in it is
           imported as a **new card**, so a board that already has the work ends
           up with two of everything. If the file is missing, sync is off: say
           so and stop.

        Rewrite the file whole and atomically: write a temporary file, then
        rename it over `tasks.json`. A half-written file is read as corrupt, and
        the app keeps showing its last good state rather than clearing the board.

        ## Picking up work

        Rows with `"requested": true` are work the user has explicitly sent to
        you. Start with those, oldest `updatedAt` first.

        ## Reporting progress

        Write `in_progress` **before you touch any code**, as its own write, and
        `review` when the pull request is open. The board's whole value is
        showing what is happening *now* — a row updated only once, at the end,
        makes a card jump from `todo` to `done` and the person watching learns
        nothing.

        When you **begin** a task, set on that row:

        - `"status": "in_progress"`
        - `"source": "claude"`
        - `"updatedAt"`: the current time, ISO-8601 with a `Z` suffix

        When you **open a pull request**, set on that row:

        - `"status": "review"`
        - `"branch"`: the branch name
        - `"prUrl"`: the pull request URL
        - `"source": "claude"` and a fresh `"updatedAt"`

        Also set the envelope's `"writer"` to `"claude"` and refresh its
        `"updatedAt"` on every write. Leave `"version"` at `1`.

        ## The status vocabulary

        Exactly these four values, and no others:

        | Status | Meaning |
        |---|---|
        | `todo` | not started |
        | `in_progress` | being worked on now |
        | `review` | a pull request is open |
        | `done` | merged or otherwise finished |

        There is no spelling for "blocked" or "cancelled". Leave such a card at
        `todo` and explain in your reply to the user.

        ## Fields you own, and fields you don't

        You own `status`, `branch` and `prUrl` — you are the only party that
        observes them.

        **Do not edit** `title`, `details`, `githubIssue` or `requested`. The app
        owns those and will overwrite whatever you put there. `column` is
        advisory, for a human reading the file; `status` is what maps back.

        ## Adding work

        Append a row with a fresh UUID `id`, `"source": "claude"` and a status of
        `todo`. It appears on the board as a new card. This is the *only* place a
        new id is ever correct.

        ## A complete file

        Every key that can appear, with `tombstones` populated so its shape is
        visible. This is `example.json`:

        ```json
        \(WorkflowTasksFile.exampleJSON)
        ```
        """
    }

    /// A pointer for the repository's own `CLAUDE.md`, so a session loads the
    /// contract without the user typing anything. Wrapped in markers so
    /// rewriting it is idempotent.
    static func claudeMemorySnippet() -> String {
        """
        \(claudeMemoryBeginMarker)
        ## Claude WM

        This repository is tracked on a Claude WM board. `\(tasksPath)`
        is the shared task list: rows with `"requested": true` are work assigned to
        you, and you report progress by setting a row's `status` to `in_progress`
        when you start and `review` when you open a PR.

        Read `\(readmePath)` for the full contract, and `\(examplePath)`
        for a complete valid file, **before** touching `tasks.json`. Nothing in it
        is validated: a wrong status, a re-minted `id` or a dropped `tombstones`
        key is accepted and quietly means something else. Never create
        `tasks.json` yourself — the app writes it.
        \(claudeMemoryEndMarker)
        """
    }

    /// Splices the snippet into an existing `CLAUDE.md` body, replacing a
    /// previous block rather than appending a second one.
    static func applyingMemorySnippet(to existing: String) -> String {
        let snippet = claudeMemorySnippet()
        guard let start = existing.range(of: claudeMemoryBeginMarker),
              let end = existing.range(of: claudeMemoryEndMarker)
        else {
            let trimmed = existing.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? snippet + "\n" : trimmed + "\n\n" + snippet + "\n"
        }
        var updated = existing
        updated.replaceSubrange(start.lowerBound..<end.upperBound, with: snippet)
        return updated
    }
}
